######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 16 13:17:38 2014
######################################################################
QT       += core gui

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets network

TARGET = socket_qt
TEMPLATE = app

# Input
HEADERS += droparea.h dropsitewindow.h
SOURCES += droparea.cpp dropsitewindow.cpp main.cpp

CONFIG += mobility
MOBILITY =
